/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-03-16 14:43:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.1.0.RELEASE.jar", Long.valueOf(1643030069469L));
    _jspx_dependants.put("/WEB-INF/views/mypage/../footer.jsp", Long.valueOf(1647244577000L));
    _jspx_dependants.put("/WEB-INF/views/mypage/../header.jsp", Long.valueOf(1647419338000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1643030069986L));
    _jspx_dependants.put("jar:file:/C:/Users/makku/Documents/PROJECT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/makku/Documents/PROJECT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/spring-webmvc-4.1.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1409771914000L));
    _jspx_dependants.put("jar:file:/C:/Users/makku/Documents/PROJECT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/spring-webmvc-4.1.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1409771914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../resources/css/join.css\">\r\n");
      out.write("<title>회원정보 수정</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border: 0px;\r\n");
      out.write("	border-bottom: 1.5px solid gray;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"../../../resources/jquery/jquery-3.6.0.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../resources/css/header.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"containerbox\">\r\n");
      out.write("   <header class=\"d-flex flex-wrap justify-content-center py-3 mb-4\">\r\n");
      out.write("     <a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none\">\r\n");
      out.write("       <span class=\"font\" id=\"bookmark\">🔖BOOKMARK</span>\r\n");
      out.write("     </a>\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   </header>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img src=\"../../resources/image/logo_transparent.png\" alt=\"\" width=\"250px\" height=\"250px\" onclick=\"javascript:location.href='/';\" style=\"cursor:pointer;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav role=\"navigation\">\r\n");
      out.write("  <ul id=\"main-menu\">\r\n");
      out.write("    <li><a href=\"/product/totalList\">전체보기</a></li>\r\n");
      out.write("    \r\n");
      out.write("      <li><a href=\"#\">베스트</a></li>\r\n");
      out.write("      \r\n");
      out.write("      <li><a href=\"#\">재구매Best</a></li>\r\n");
      out.write("      \r\n");
      out.write("       <li><a href=\"#\">신제품</a></li>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#bookmark\").click(function(){\r\n");
      out.write("    alert(\"Ctrl+D키를 누르시면 즐겨찾기에 추가하실 수 있습니다.\");\r\n");
      out.write("});\r\n");
      out.write("function categoryEdit(){\r\n");
      out.write("	open('http://localhost:8080/category/categorySequence','배너 추가','width=400px,height=200px,status=false');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("	<h2 class=\"cen\">회원 정보 수정🔏</h2>\r\n");
      out.write("<br>\r\n");
      out.write("	<div class=\"modifyInfo\">*아이디를 제외한 회원정보만 수정가능합니다.</div>\r\n");
      out.write("	<form id=\"modifyform\" action=\"modify\" commandName=\"formData\" class=\"validation-form\" method=\"post\">\r\n");
      out.write("		\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>이름</th>\r\n");
      out.write("				<td><input type=\"text\" class=\"form-control\" id=\"member_name\" name=\"member_name\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"required>\r\n");
      out.write("				<br>\r\n");
      out.write("				<span class=\"member_name regex\" style=\"text-align:left;\"></span>\r\n");
      out.write("				<input type=\"hidden\" id=\"nameDoubleChk\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>닉네임</th>\r\n");
      out.write("				<td><input type=\"text\" class=\"form-control\" id=\"member_nickname\" name=\"member_nickname\" \r\n");
      out.write("				placeholder=\"한글/영문/숫자 포함  2~10자 \" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("				<br>\r\n");
      out.write("				<span class=\"point successNameChk\"></span>\r\n");
      out.write("				<input type=\"hidden\" id=\"nicknameDoubleChk\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>아이디</th>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <input type=\"hidden\" id=\"member_id\" name=\"member_id\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>현재 이메일</th>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				<span class=\"glyphiconAddress glyphicon-plusAddress plusIconAddress\">&nbsp; &nbsp;이메일 변경하기</span>\r\n");
      out.write("				<span class=\"glyphiconAddress glyphicon-minusAddress plusIconAddress\" style=\"display:none\">&nbsp; &nbsp;취소하기</span>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr class=\"emailtoggle\" style=\"display:none\">\r\n");
      out.write("				<th class=\"modi\">변경할 이메일</th>\r\n");
      out.write("				<td><input type=\"text\" name=\"email\" id=\"email\" value=\"\" style=\"width:100px; text-align:left;\">\r\n");
      out.write("				<span id=\"middle\">@</span>\r\n");
      out.write("				<input type=\"text\" name=\"domain\" id=\"domain\" value=\"\" style=\"width: 100px;\"> \r\n");
      out.write("				<select style=\"width: 100px; margin-right: 10px\" name=\"selectEmail\" id=\"selectEmail\">\r\n");
      out.write("						<option value=\"1\">직접입력</option>\r\n");
      out.write("						<option value=\"\" selected>선택하세요</option>\r\n");
      out.write("						<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("						<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("						<option value=\"hotmail.com\">hotmail.com</option>\r\n");
      out.write("						<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("						<option value=\"yahoo.co.kr\">yahoo.co.kr</option>\r\n");
      out.write("						<option value=\"empas.com\">empas.com</option>\r\n");
      out.write("						<option value=\"dreamwiz.com\">dreamwiz.com</option>\r\n");
      out.write("						<option value=\"freechal.com\">freechal.com</option>\r\n");
      out.write("						<option value=\"lycos.co.kr\">lycos.co.kr</option>\r\n");
      out.write("						<option value=\"korea.com\">korea.com</option>\r\n");
      out.write("						<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("						<option value=\"hanmir.com\">hanmir.com</option>\r\n");
      out.write("						<option value=\"paran.com\">paran.com</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				<input type=\"hidden\" id=\"member_email\" name=\"member_email\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"emailDoubleChk\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>휴대폰번호</th>\r\n");
      out.write("				<td><input type=\"text\" class=\"form-control\" id=\"member_phone\"\r\n");
      out.write("					name=\"member_phone\" placeholder=\"-를 제외한 숫자만 입력해주세요\" style=\"text-align:left;\" \r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("					<br>\r\n");
      out.write("					<span class=\"member_phone regex\" style=\"text-align:left;\"></span>\r\n");
      out.write("					<input type=\"hidden\" id=\"phoneDoubleChk\">\r\n");
      out.write("					</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>현재 주소</th>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				<span class=\"glyphicon glyphicon-plus plusIcon\">&nbsp; &nbsp;주소 변경하기 </span>\r\n");
      out.write("				<span class=\"glyphicon glyphicon-minus plusIcon\" style=\"display:none\">&nbsp; &nbsp;취소하기</span>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"display:none\">\r\n");
      out.write("				<th class=\"modi\">변경할 주소</th>\r\n");
      out.write("\r\n");
      out.write("				<td><input class=\"form-control\" style=\"width: 30%; display: inline;\" type=\"text\" name=\"postcode\" id=\"postcode\" placeholder=\"우편번호\">\r\n");
      out.write("				<input type=\"button\" onclick=\"execDaumPostcode()\" value=\"우편번호 찾기\">\r\n");
      out.write("				<br>\r\n");
      out.write("				 <input class=\"form-control\" type=\"text\" name=\"address\" id=\"address\" style=\"width: 60%; display: inline; margin-top: 5px;\"\r\n");
      out.write("					placeholder=\"도로명 주소\" style=\"text-align:left;\"> \r\n");
      out.write("				<br>\r\n");
      out.write("				 <input class=\"form-control\" style=\"width: 40%; display: inline; margin-top: 5px;\" type=\"text\"\r\n");
      out.write("				id=\"detailAddress\" name=\"detailAddress\" placeholder=\"상세주소\" style=\"text-align:left;\">\r\n");
      out.write("				<input type=\"hidden\" name=\"member_address\" id=\"member_address\" value=\"\">\r\n");
      out.write("				</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<button class=\"btn1 btn-primary btn-lg btn-block\" type=\"button\" id=\"signupbtn\" name=\"signup\">수정하기</button>\r\n");
      out.write("		<button class=\"btn2 btn-primary btn-lg btn-block\" onclick=\"#\">취소하기</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../resources/css/header.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".foot {\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mainfoot{\r\n");
      out.write("	color:black;\r\n");
      out.write("	font-size:15px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"footerContainer\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"footerLine\">\r\n");
      out.write("		<div class=\"footerInformation\">\r\n");
      out.write("			<div class=\"first\">\r\n");
      out.write("				<p class=\"mainfoot\">밀슐랭</p>\r\n");
      out.write("				<p class=\"foot\">COMPANY NAME : 밀슐랭 OWNER : 윤가영, 김주평</p>\r\n");
      out.write("				<p class=\"foot\">COMPANY REG.NO : 000-00-0000</p>\r\n");
      out.write("				<p class=\"foot\">NETWORK REG.NO : 2022-경기수원-0호 [BUSINESS INFO]</p>\r\n");
      out.write("				<p class=\"foot\">TEL : 0000-0000 ADDRESS : 경기도 수원시 아이메카 빌딩</p>\r\n");
      out.write("				<p class=\"foot\">CPO : 윤김(GREEN@GREEAN.COM)</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"second\"></div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"third\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("	//이름 유효성검사\r\n");
      out.write("	$(\"#member_name\").on(\"input\",function(){\r\n");
      out.write("	    var regex = /[가-힣]{2,}/;\r\n");
      out.write("	    var result = regex.exec($(\"#member_name\").val());\r\n");
      out.write("	    \r\n");
      out.write("	    if(result != null){\r\n");
      out.write("	       $(\".member_name.regex\").html(\"\");  \r\n");
      out.write("	    }else{\r\n");
      out.write("	        $(\".member_name.regex\").html(\"한글만 입력 가능합니다.\");\r\n");
      out.write("	        $(\".member_name.regex\").css(\"color\",\"red\");\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	//비밀번호 유효성검사\r\n");
      out.write("	$(\"#member_pwd\").on(\"input\",function(){\r\n");
      out.write("	    var regex = /^[A-Za-z\\d]{8,21}$/;\r\n");
      out.write("	    var result = regex.exec($(\"#member_pwd\").val())\r\n");
      out.write("	    \r\n");
      out.write("	    if(result != null){\r\n");
      out.write("	        $(\".member_pwd.regex\").html(\"\");\r\n");
      out.write("	    }else{\r\n");
      out.write("	        $(\".member_pwd.regex\").html(\"비밀번호는 영문 대소문자,숫자 8자 이상 20자 이하로 설정해주세요.\");\r\n");
      out.write("	        $(\".member_pwd.regex\").css(\"color\",\"	red\")\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//비밀번호 확인    \r\n");
      out.write("	   $(\"#rePassword\").on(\"input\",function(){\r\n");
      out.write("		   \r\n");
      out.write("		   let member_pwd = document.getElementById(\"member_pwd\").value\r\n");
      out.write("		   let rePassword = document.getElementById(\"rePassword\").value 		   \r\n");
      out.write("\r\n");
      out.write("	        if(rePassword.length > 2 && member_pwd == rePassword){\r\n");
      out.write("	        	$(\".rePassword.regex\").html(\"비밀번호가 일치합니다\"); \r\n");
      out.write("	        	  $(\".rePassword.regex\").css(\"color\",\"green\"); \r\n");
      out.write("	          \r\n");
      out.write("	        }else{\r\n");
      out.write("	         $(\".rePassword.regex\").html(\"비밀번호가 일치하지않습니다\"); \r\n");
      out.write("	         $(\".rePassword.regex\").css(\"color\",\"red\"); \r\n");
      out.write("	        }\r\n");
      out.write("	   });\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	//전화번호 유효성검사\r\n");
      out.write("         $(\"#member_phone\").on(\"input\",function(){\r\n");
      out.write("              var regex = /^01\\d\\d{3,4}\\d{4}$/;\r\n");
      out.write("              var result = regex.exec($(\"#member_phone\").val());\r\n");
      out.write("             \r\n");
      out.write("             if(result != null){\r\n");
      out.write("                $(\".member_phone.regex\").html(\"\");  \r\n");
      out.write("             }else{\r\n");
      out.write("                 $(\".member_phone.regex\").html(\"올바른 번호가 아닙니다\");\r\n");
      out.write("                 $(\".member_phone.regex\").css(\"color\",\"red\"); \r\n");
      out.write("             }\r\n");
      out.write("             \r\n");
      out.write("         })\r\n");
      out.write("	\r\n");
      out.write("	//이메일  합치기  \r\n");
      out.write("	//blur 이벤트는 사용자가 폼에 입력을 마치고 커서가 해당 폼을 벗어났을 때 실행되며, change 이벤트는 폼에 변화가 감지되었을 때 실행된다.\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write(" 	$(\"#email\").blur(function(){\r\n");
      out.write("		email();	\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\"select[name=selectEmail]\").change(function(){\r\n");
      out.write("		email();	\r\n");
      out.write("	}); \r\n");
      out.write("\r\n");
      out.write("	function email() {\r\n");
      out.write("		const email = $(\"#email\").val();\r\n");
      out.write("		const middle = $(\"#middle\").text();\r\n");
      out.write("		const domain = $(\"#domain\").val();\r\n");
      out.write("		if(email != \"\" && domain != \"\") {\r\n");
      out.write("			$(\"#member_email\").val(email+middle+domain);\r\n");
      out.write("		}\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	//주소 합치기\r\n");
      out.write("	$(\"#postcode\").change(function(){\r\n");
      out.write("		addr();	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#address\").change(function(){\r\n");
      out.write("		addr();	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#detailAddress\").change(function(){\r\n");
      out.write("		addr();	\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	function addr() {\r\n");
      out.write("		const postcode = $(\"#postcode\").val();\r\n");
      out.write("		const address = $(\"#address\").val();\r\n");
      out.write("		const detailAddress = $(\"#detailAddress\").val();\r\n");
      out.write("		if(postcode != \"\" && address != \"\") {\r\n");
      out.write("			$(\"#member_address\").val(postcode+address+detailAddress);\r\n");
      out.write("		}\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	//닉네임 중복 체크\r\n");
      out.write("	$(\"#member_nickname\").blur(function(){ \r\n");
      out.write("		var member_nickname = $(\"#member_nickname\").val();\r\n");
      out.write("		var regex = /[0-9]|[a-z]|[A-Z]|[가-힣]/;\r\n");
      out.write("		var result = regex.exec($(\"#member_nickname\").val());\r\n");
      out.write("		\r\n");
      out.write("		if(member_nickname == \"\" || member_nickname.length<2){ \r\n");
      out.write("			\r\n");
      out.write("			$(\".successNameChk\").text(\"닉네임은 한글, 영문, 숫자만 가능하며 2-10자리 가능합니다.\");\r\n");
      out.write("			$(\".successNameChk\").css(\"color\", \"red\"); \r\n");
      out.write("			$(\"#nicknameDoubleChk\").val(\"false\"); \r\n");
      out.write("			$(\"#nicknameDoubleChk\").val(\"false\"); \r\n");
      out.write("		\r\n");
      out.write("		}else{ \r\n");
      out.write("			 \r\n");
      out.write("			$.ajax({ \r\n");
      out.write("					\r\n");
      out.write("					 url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/nameCheck?member_nickname='+ member_nickname, \r\n");
      out.write("					 type : 'post', \r\n");
      out.write("					 dataType: \"json\",\r\n");
      out.write("					 cache : false, \r\n");
      out.write("					 success : function(data) { \r\n");
      out.write("						 if (data == 0 && result != null) {\r\n");
      out.write("							 $(\".successNameChk\").text(\"사용가능한 닉네임입니다.\"); \r\n");
      out.write("						 	 $(\".successNameChk\").css(\"color\", \"green\"); \r\n");
      out.write("						 	 $(\"#nicknameDoubleChk\").val(\"true\"); \r\n");
      out.write("						\r\n");
      out.write("						 } else if(result == null){\r\n");
      out.write("			\r\n");
      out.write("							 $(\".successNameChk\").text(\"닉네임은 한글, 영문, 숫자만 가능하며 2-10자리 가능합니다.\");\r\n");
      out.write("							 $(\".successNameChk\").css(\"color\", \"red\"); \r\n");
      out.write("							 $(\"#nicknameDoubleChk\").val(\"false\"); \r\n");
      out.write("							 \r\n");
      out.write("						 }else{ \r\n");
      out.write("							 $(\".successNameChk	\").text(\"사용중인 닉네임입니다.\");\r\n");
      out.write("							 $(\".successNameChk\").css(\"color\", \"red\"); \r\n");
      out.write("							 $(\"#nicknameDoubleChk\").val(\"false\"); \r\n");
      out.write("							 } \r\n");
      out.write("						 }, error : function() {\r\n");
      out.write("							 console.log(member_nickname);\r\n");
      out.write("							 console.log(\"실패\"); \r\n");
      out.write("							 $(\".successNameChk\").text(\"특수문자 입력 불가능합니다.\");\r\n");
      out.write("							 $(\".successNameChk\").css(\"color\", \"red\"); \r\n");
      out.write("							 $(\"#nicknameDoubleChk\").val(\"false\"); \r\n");
      out.write("							 }\r\n");
      out.write("						 });\r\n");
      out.write("					} });\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	// 우편번호 서비스\r\n");
      out.write("    function execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	//이메일 주소 입력\r\n");
      out.write("	 $(function(){ $('#selectEmail').change(function(){\r\n");
      out.write("	   if($('#selectEmail').val() == \"1\"){\r\n");
      out.write("	    $(\"#domain\").val(\"\"); //값 초기화\r\n");
      out.write("	    $(\"#domain\").prop(\"readonly\",false); //활성화\r\n");
      out.write("	   } else if($('#selectEmail').val() == \"\"){\r\n");
      out.write("	    $(\"#domain\").val(\"\"); //값 초기화\r\n");
      out.write("	    $(\"#domain\").prop(\"readonly\",true); //textBox 비활성화\r\n");
      out.write("	   } else {\r\n");
      out.write("	    $(\"#domain\").val($('#selectEmail').val()); //선택값 입력\r\n");
      out.write("	    $(\"#domain\").prop(\"readonly\",true); //비활성화\r\n");
      out.write("	    email();\r\n");
      out.write("	   }\r\n");
      out.write("	  });\r\n");
      out.write("	 });\r\n");
      out.write("	\r\n");
      out.write("	//폼 제출전 유효성 검사\r\n");
      out.write("	  $(\"#signupbtn\").on(\"click\",function(){\r\n");
      out.write("		  \r\n");
      out.write("	  /*  var id = $(\"#id\").val();\r\n");
      out.write("   	   var pw = $(\"#pw\").val();\r\n");
      out.write("   	   var name = $(\"#name\").val();\r\n");
      out.write("   	   var phone = $(\"#phone\").val();\r\n");
      out.write("   	   var email = $(\"#email\").val();	   */\r\n");
      out.write("		  \r\n");
      out.write("   	   var pw =  document.getElementById('member_pwd').value\r\n");
      out.write("   	   var name =  document.getElementById('member_name').value\r\n");
      out.write("   	   var nickname = document.getElementById('member_nickname').value\r\n");
      out.write("   	   var email = document.getElementById('member_email').value\r\n");
      out.write("	   var idDoubleChk = document.getElementById('idDoubleChk').value\r\n");
      out.write("	   var nicknameDoubleChk = document.getElementById('nicknameDoubleChk').value\r\n");
      out.write("   	   \r\n");
      out.write("   		   	   \r\n");
      out.write("   	   var pwregex = /^[A-Za-z\\d]{8,21}$/;\r\n");
      out.write("   	   var nameregex = /[가-힣]{2,}/;\r\n");
      out.write("   	   var nicknameregex = /[0-9]|[a-z]|[A-Z]|[가-힣]/;\r\n");
      out.write("   	   var emailregex = /.+@[a-z]+(\\.[a-z]+){1,2}$/;\r\n");
      out.write("   	   var a = true;\r\n");
      out.write("   	   var b = false;\r\n");
      out.write("   	 \r\n");
      out.write("   	   var nameregex = nameregex.exec(name);\r\n");
      out.write("	   if(nameregex == null){\r\n");
      out.write("		   alert(\"이름양식을 다시 확인해주세요\");\r\n");
      out.write("		   retrun;\r\n");
      out.write("	   }\r\n");
      out.write("	   \r\n");
      out.write("	   var nicknameregex = nicknameregex.exec(nickname);\r\n");
      out.write("   	   if(nicknameregex == null){\r\n");
      out.write("   		   alert(\"닉네임양식을 다시 확인해주세요\");\r\n");
      out.write("   		   retrun;\r\n");
      out.write("   	   }\r\n");
      out.write("   	   \r\n");
      out.write("   	   \r\n");
      out.write("   	   var pwregex = pwregex.exec(pw);\r\n");
      out.write("   	   if(pwregex == null){\r\n");
      out.write("   		   alert(\"비밀번호양식을 다시 확인해주세요\");\r\n");
      out.write("   		   retrun;\r\n");
      out.write("   	   }\r\n");
      out.write("   	  var emailregex = emailregex.exec(email);\r\n");
      out.write("	   if(emailregex == null){\r\n");
      out.write("		   alert(\"이메일양식을 다시 확인해주세요\");\r\n");
      out.write("		   retrun;\r\n");
      out.write("	   }\r\n");
      out.write("   	   \r\n");
      out.write("        //빈칸 없을 때 제출.\r\n");
      out.write("   	   $(\"#modifyform\").submit();\r\n");
      out.write("       	   \r\n");
      out.write("\r\n");
      out.write("   })\r\n");
      out.write("   \r\n");
      out.write("   //주소 숨기기\r\n");
      out.write("   $(\".plusIcon\").on(\"click\",function(){\r\n");
      out.write("	  var obj = $(this);\r\n");
      out.write("	  if( obj.hasClass(\"glyphicon-plus\") ){\r\n");
      out.write("	    obj.hide();\r\n");
      out.write("	    obj.next().show();            \r\n");
      out.write("	    obj.parent().parent().next().show();\r\n");
      out.write("	  }else if( obj.hasClass(\"glyphicon-minus\")){\r\n");
      out.write("	     obj.hide();\r\n");
      out.write("	     obj.prev().show();\r\n");
      out.write("	     obj.parent().parent().next().hide();\r\n");
      out.write("	  }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("  //이메일  숨기기\r\n");
      out.write("   $(\".plusIconAddress\").on(\"click\",function(){\r\n");
      out.write("	  var obj = $(this);\r\n");
      out.write("	  if( obj.hasClass(\"glyphicon-plusAddress\") ){\r\n");
      out.write("	    obj.hide();\r\n");
      out.write("	    obj.next().show();            \r\n");
      out.write("	    obj.parent().parent().next().show();\r\n");
      out.write("	  }else if(obj.hasClass(\"glyphicon-minusAddress\")){\r\n");
      out.write("	     obj.hide();\r\n");
      out.write("	     obj.prev().show();\r\n");
      out.write("	     obj.parent().parent().next().hide();\r\n");
      out.write("	  }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	 ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    \r\n");
          out.write("     ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("     \r\n");
          out.write("     ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/mypage/../header.jsp(23,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty authInfo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("     	<ul class=\"navheader\">\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"");
          if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\"  aria-current=\"page\">로그인</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"");
          if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\" >회원가입</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"#\">주문조회</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"#\">장바구니</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"#\">카테고리추가</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"#\">카테고리삭제</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"javascript:categoryEdit();\">카테고리순서변경</a></li>\r\n");
          out.write("     	</ul>\r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/views/mypage/../header.jsp(25,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/member/login");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/views/mypage/../header.jsp(26,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/member/joinChoice");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/mypage/../header.jsp(35,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authInfo.member_id  eq 'MEALADMIN' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("     	 <ul class=\"navheader\">\r\n");
          out.write("	       <li class=\"navheader userinfo\">관리자님 안녕하세요🙌</li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"");
          if (_jspx_meth_c_005furl_005f2(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\"  aria-current=\"page\">로그아웃</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"");
          if (_jspx_meth_c_005furl_005f3(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\" >관리자페이지</a></li>\r\n");
          out.write("     	</ul>\r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /WEB-INF/views/mypage/../header.jsp(38,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/logout");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /WEB-INF/views/mypage/../header.jsp(39,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/admin/admin/${authInfo.member_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("       <ul class=\"navheader\">\r\n");
          out.write("	       <li class=\"navheader userinfo\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authInfo.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 안녕하세요💗</li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"");
          if (_jspx_meth_c_005furl_005f4(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\"  aria-current=\"page\">로그아웃</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"");
          if (_jspx_meth_c_005furl_005f5(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\" >마이페이지</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"#\" >주문조회</a></li>\r\n");
          out.write("	       <li class=\"navheader\"><a href=\"#\">장바구니</a></li>\r\n");
          out.write("     </ul>\r\n");
          out.write("     \r\n");
          out.write("     \r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/mypage/../header.jsp(46,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/logout");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/mypage/../header.jsp(47,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/mypage/mypage/${authInfo.member_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/mypage/../header.jsp(72,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty menu1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	    <li><a href=\"#\">&nbsp;&nbsp;&nbsp;테마별&nbsp;&nbsp;</a>\r\n");
          out.write("	    	<ul id=\"sub-menu\">\r\n");
          out.write("	    		");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	    	</ul>\r\n");
          out.write("	    </li>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/mypage/../header.jsp(75,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("menu1");
      // /WEB-INF/views/mypage/../header.jsp(75,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/../header.jsp(75,7) '${menu1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${menu1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			       <li><a href=\"/product/categoryList/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu1.category_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" aria-label=\"subemnu\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu1.category_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/mypage/../header.jsp(81,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty menu2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	    <li><a href=\"#\">사이드디쉬</a>\r\n");
          out.write("	      <ul id=\"sub-menu\">\r\n");
          out.write("		        ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	      </ul>\r\n");
          out.write("	    </li>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/mypage/../header.jsp(84,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("menu2");
      // /WEB-INF/views/mypage/../header.jsp(84,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/../header.jsp(84,10) '${menu2}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${menu2}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				   <li><a href=\"/product/categoryList/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu2.category_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" aria-label=\"subemnu\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu2.category_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/mypage/../header.jsp(90,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty menu3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	    <li><a href=\"#\">브랜드관</a>\r\n");
          out.write("	      <ul id=\"sub-menu\">\r\n");
          out.write("		        ");
          if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	      </ul>\r\n");
          out.write("	    </li>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/mypage/../header.jsp(93,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("menu3");
      // /WEB-INF/views/mypage/../header.jsp(93,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/../header.jsp(93,10) '${menu3}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${menu3}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				   <li><a href=\"/product/categoryList/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu3.category_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" aria-label=\"subemnu\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu3.category_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
